// All3DTxt.h: Schnittstelle für die Klasse CAll3DTxt.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_ALL3DTXT_H__01AD9086_BAD1_11D3_B8D6_0000E8699C86__INCLUDED_)
#define AFX_ALL3DTXT_H__01AD9086_BAD1_11D3_B8D6_0000E8699C86__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CAll3DTxt  
{
public:
	CAll3DTxt();
	virtual ~CAll3DTxt();

};

#endif // !defined(AFX_ALL3DTXT_H__01AD9086_BAD1_11D3_B8D6_0000E8699C86__INCLUDED_)
