#ifndef _MY_TYPE_
#define _MY_TYPE_
/////////////////////////////////////////////////////////////////////////////
// Some definitions needed
/////////////////////////////////////////////////////////////////////////////
const int TRUE  = 1;
const int FALSE = 0;
typedef int BOOL ;

const float MY_PI = 3.141592654;
const float MY_RAD = MY_PI * 2;

const int SCREEN_X = 640;
const int SCREEN_Y = 480;


enum SCREENDEFINTIONS
{
    ModeText = 3,
    Mode320x200x256 = 19
};





#endif



