#ifndef __VESASLAVE_ERROR__
#define __VESASLAVE_ERROR__

const char * No_Videomodes_found = "No Video-Modes found\n";
const char * No_Vbe2_or_greater_found = "No VBE 2.0 or greater found\n";
const char * Initing_Hermes_went_wrong = "Error while Initializing Hermes\n";
const char * Cant_Allocate_VirtualScreens = "Can't Allocate Virtual Screens\n";
const char * Cant_Allocate_Palette_Array = "Can't Alocate Palette-Array\n";
const char * Could_not_Convert = "Could not Convert between Internal/External Image Formats\n";
const char * No_Valid_ScreenPointer = "Screen Pointer not Valid\n";
const char * Mode_not_Valid = "Mode not valid\n";
const char * Could_not_find_Converter = "Couldn't Find Converter\n";


#endif

